name: 'Deploy to Heroku'
description: 'Deploy a zip file to a Heroku app'
inputs:
  artifact-path:
    description: 'The path to the artifact to deploy.'
    required: true
  app:
    description: 'The name of the Heroku app'
    required: true
  token:
    description: 'An oauth api token from Heroku with permission to deploy the app.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
