name: 'Deploy to Heroku'
description: 'Deploy a zip file to a heroku app'
inputs:
  artifact-path:
    description: 'The path to the artifact to deploy.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
